// <auto-generated />
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(AcademyDbContext))]
    partial class AcademyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EstimatedTime");

                    b.Property<int>("StudentId");

                    b.Property<int>("TimeSpent");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Projects");

                    b.HasData(
                        new { Id = 1, EstimatedTime = 55, StudentId = 1, TimeSpent = 22, Title = "JavaScript" },
                        new { Id = 2, EstimatedTime = 65, StudentId = 1, TimeSpent = 33, Title = "EntityFramework" },
                        new { Id = 3, EstimatedTime = 25, StudentId = 1, TimeSpent = 5, Title = "SqlDatabase" },
                        new { Id = 4, EstimatedTime = 25, StudentId = 2, TimeSpent = 22, Title = "SqlDatabase" },
                        new { Id = 5, EstimatedTime = 55, StudentId = 2, TimeSpent = 22, Title = "DataDriven" }
                    );
                });

            modelBuilder.Entity("Domain.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Academy");

                    b.Property<int>("Age");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new { Id = 1, Academy = 2, Age = 26, FirstName = "Goce", LastName = "Kabov" },
                        new { Id = 2, Academy = 3, Age = 28, FirstName = "Kire", LastName = "Davitkov" }
                    );
                });

            modelBuilder.Entity("Domain.Models.Project", b =>
                {
                    b.HasOne("Domain.Models.Student", "Student")
                        .WithMany("Projects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
